services:
  db:
    image: postgres:15
    container_name: defi-crypta-pay-bot-db
    restart: always
    environment:
      POSTGRES_DB: defi_bot_crypta
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
